version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "80:8069"
    networks:
      - odoo_network
    volumes:
      - ./odoo-data:/var/lib/odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - odoo_network
    volumes:
      - ./pg-data:/var/lib/postgresql/data
networks:
  odoo_network:
    driver: bridge
